version: "3"

services:
  db:
    container_name: postgres-container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zzz123
  pgAdmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:6.11
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ignas@admin.com
      PGADMIN_DEFAULT_PASSWORD: zzz123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
